-- Add indicator_data column to signals table for storing calculated indicator values
-- This enables custom indicator visualization on charts without frontend recalculation

-- Add indicator_data column
ALTER TABLE signals ADD COLUMN indicator_data JSONB;

-- Create GIN index for efficient JSONB queries
CREATE INDEX idx_signals_indicator_data ON signals USING gin(indicator_data);

-- Add column comment for documentation
COMMENT ON COLUMN signals.indicator_data IS
'Calculated indicator values for chart visualization.
Format: {"indicator_id": [{"x": timestamp, "y": value, "y2"?: value, ...}]}
Example: {"rsi_14": [{"x": 1704470400000, "y": 45.2}], "bb_20_2": [{"x": 1704470400000, "y": 44000, "y2": 43500, "y3": 43000}]}
Generated by series code execution when signal is created. NULL for signals created before this feature.';
